### ISSUE TITLE
Crash when trying the sample , and nothing occurs when fixing it

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [ajkh35/ContactsDemo#2] opened 2017-08-26 18:48 UTC
You've set targetSdk to 23, so you have to handle runtime permissions:
https://developer.android.com/training/permissions/requesting.html

Because you didn't you get a crash of this sort on the sample of the repo:
                                                                           java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.ajay.contacts_4/com.example.ajay.contacts_4.MainActivity}: java.lang.SecurityException: Permission Denial: opening provider com.android.providers.contacts.ContactsProvider2 from ProcessRecord{ecd6317 4450:com.example.ajay.contacts_4/u0a83} (pid=4450, uid=10083) requires android.permission.READ_CONTACTS or android.permission.WRITE_CONTACTS

I changed it to 22, but then nothing occurs.
I looked at the contacts app, and nothing is there (tested on emulator) .

**Comment by ajkh35** [comment] 2017-08-26 19:48
Hi there,
yeah this is an issue since the marshmallow update. Well not so much an issue from the android part as in the run time permissions whenever the app tries to access the android os resources. Check this link out [https://developer.android.com/training/permissions/requesting.html](url)

**Comment by AndroidDeveloperLB** [comment] 2017-08-26 19:59
Again, this is an issue only if your targetSdk is 23 and above.
Setting it to 22 will fix it, as all permissions are given on install.
The real issue is that the app doesn't do anything when started.

**Comment by ajkh35** [comment] 2017-08-26 20:03
Actually this PoC was intended more from code derivation point of view, I will update the repository with the required version of android.

**Comment by AndroidDeveloperLB** [comment] 2017-08-26 20:26
Again, the version isn't the issue. The app itself doesn't do anything.

**Comment by ajkh35** [comment] 2017-08-26 20:32
There were not many people before who were checking out the app per se so much as the code, I will add a feedback for the background task.

**Comment by AndroidDeveloperLB** [comment] 2017-08-26 20:34
As I understand, this sample is supposed to show how to create a contacts account, and then put some data into it, right?

**Comment by ajkh35** [comment] 2017-08-26 20:37
Yup, a progress dialog should do the trick.

**Comment by AndroidDeveloperLB** [comment] 2017-08-27 21:53
Say, you seem to be an expert in address book API on Android.
Can you please help me on StackOverflow? I'm trying to update a contact photo, that I got its data from a query of WhatsApp contacts:
https://stackoverflow.com/q/45894991/878126
For me it works fine, but for a small number of users, it doesn't, and I have no idea what's the cause for this.

**Comment by ajkh35** [comment] 2017-09-06 05:49
Sorry for the late reply, had a bit of bad health. I can only suggest a general approach right now. It would be to find the contact through raw contact to prevent any duplicacy then apply the batch to display image. Now sometimes it doesn't work that's why I recommend you use raw contact id to find the contact same as I checked for existing contact.

**Comment by AndroidDeveloperLB** [comment] 2017-09-18 14:52
I see. Thanks.

**Comment by AndroidDeveloperLB** [comment] 2017-10-05 20:24
Was this issue fixed?
If not, why close it?

**Comment by ajkh35** [comment] 2017-10-07 13:15
Okay then do let me know of any issues.

**Comment by AndroidDeveloperLB** [comment] 2017-10-07 18:32
Doesn't seem it was fixed or even updated.
Still doesn't do anything, even if I fix the permission issue.

It seems to have a crash at some point in the background thread:

10-07 21:31:16.867 15579-15681/com.example.ajay.contacts_4 E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #1
                                                                             Process: com.example.ajay.contacts_4, PID: 15579
                                                                             java.lang.RuntimeException: An error occurred while executing doInBackground()
                                                                                 at android.os.AsyncTask$3.done(AsyncTask.java:353)
                                                                                 at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
                                                                                 at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
                                                                                 at java.util.concurrent.FutureTask.run(FutureTask.java:271)
                                                                                 at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
                                                                                 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
                                                                                 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
                                                                                 at java.lang.Thread.run(Thread.java:764)
                                                                              Caused by: java.lang.IndexOutOfBoundsException: Index: 259, Size: 259
                                                                                 at java.util.ArrayList.get(ArrayList.java:437)
                                                                                 at com.example.ajay.contacts_4.MainActivity$1.doInBackground(MainActivity.java:36)
                                                                                 at com.example.ajay.contacts_4.MainActivity$1.doInBackground(MainActivity.java:28)
                                                                                 at android.os.AsyncTask$2.call(AsyncTask.java:333)
                                                                                 at java.util.concurrent.FutureTask.run(FutureTask.java:266)
                                                                                 at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245) 
                                                                                 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162) 
                                                                                 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636) 
                                                                                 at java.lang.Thread.run(Thread.java:764)

**Comment by ajkh35** [comment] 2018-06-14 16:14
Hi,
I see that the numbers array is out of bounds. Probably your contact does not have a number. This is probably just a null check exception.

**Comment by mohamad6262** [comment] 2018-06-19 04:55
hi
when i click on the app icon in the contact book, i want to intent to the app with contact id. then i use this id to show my contact detail in my app. what am I do? where is Intent.putExtra and intent.getIntent Palce?

**Comment by ajkh35** [comment] 2018-06-27 10:09
Check to see ContactsManager.java, it only adds a contact. See the isAlreadyRegistsred() method, I think that might be what you are looking for.

**Comment by mohamad6262** [comment] 2018-07-07 17:27
hi
Is there a way to get the contact id of the clicked a contact from the ViewingActivity? like intent ....

 when ViewingActivity launches I want to get id of the contact which's app connection was clicked in phonebook...

is there any way to get Contact id in the ViewingActivity?

**Comment by ajkh35** [comment] 2018-07-07 20:10
I think you can do Intent intent = getIntent() and then intent.getData() to retrieve all the necessary information. Just call these methods in the onCreate() method of the ViewingActivity.

**Comment by mohamad6262** [comment] 2018-07-10 07:17
I solved my problem with your help. Thank you ....

**Comment by mohamad6262** [comment] 2018-07-10 07:21
is there any way to remove app icon from specific contact with contact id?

ContactsManager.java adds a contact, but how can I remove it?

**Comment by ajkh35** [comment] 2018-07-10 10:52
Look for contacts.xml in the res folder. I think you will find icon as well as display data within the ContactsDataKind xml tag.

**Comment by mohamad6262** [comment] 2018-07-10 11:14
no. actually i want remove specific contact that i added with my app. in contactManager I can add a contact but i cant remove it. where can i remove the contact? what methods?

**Comment by ajkh35** [comment] 2018-07-10 13:08
I didn't actually implement the delete contact id, you can probably work around with this 
ArrayList ops = new ArrayList(); String[] args = new String[] {id}; 
// id is raw contact id
ops.add(ContentProviderOperation.newDelete(RawContacts.CONTENT_URI).withSelection(RawContacts._ID + "=?", args) .build());

**Comment by AndroidDeveloperLB** [comment] 2018-07-10 13:10
Guys please move this conversation elsewhere. It doesn't have anything to do with the topic of the thread.
I get emails for each of what you write, hoping anyone got it working...

**Comment by ajkh35** [comment] 2018-07-10 13:34
Think the issue is solved mostly, I will close the issue. :)

**Comment by AndroidDeveloperLB** [comment] 2018-07-10 13:43
How is it solved?
Cloning the project and running it will now work without any crash?

**Comment by AndroidDeveloperLB** [comment] 2018-07-10 13:44
I can see the repository hasn't been updated in a long time, still. This issue shouldn't be closed.

**Comment by mohamad6262** [comment] 2018-07-23 03:58
hi
for Android 6.0 or above, app cant sync contact book and cant add account to contact. where is the problem?

**Comment by ajkh35** [comment] 2018-07-23 04:35
So I think I will just leave the issue open. Android 6.0 is for the demo application in case you try to run the application directly. There is no provision for runtime permissions.

**Comment by ajkh35** [comment] 2020-04-17 23:24
Hello,
the old master branch has been deprecated. Please switch to the new "ContactsDemoV2" branch.

Thanks & regards

**Comment by AndroidDeveloperLB** [comment] 2020-04-18 05:42
For some reason the repository page says it needs a server.
But the sample was about contacts of the device, in the address book, to show how to create a new account and put contacts data into it.
What is going on? 
All I wanted to check out is a sample that's about the address book...

**Comment by ajkh35** [comment] 2020-04-18 07:04
Hi,

You can just replace server response with a dummy list. I will add this to the repository page.

Thanks

**Comment by AndroidDeveloperLB** [comment] 2020-04-18 07:06
Is it possible to run the sample without setting any server ? Meaning to run its single APK just on the Android device and that's it?

**Comment by ajkh35** [comment] 2020-04-18 07:12
Yes you can run it without the server. You will need to change the **SyncAdapter** just little bit. I am updating it and you should be able to see the changes required on the repository page in a little while.

**Comment by AndroidDeveloperLB** [comment] 2020-04-18 17:00
Too bad. Was hoping for a minimal sample. :(
Can you please make a minimal sample ? Or point me to one?

**Comment by ajkh35** [comment] 2020-04-18 18:17
No I am sorry I cannot make a sample at this time. I had been working on this for quite some time along with my office work and so on. I do not know of any other sample.

But I presume you are not new to this. You know the basic ins and outs. What I basically did was use AggregationExceptions to manually aggregate the raw contacts. That's the only major difference between the last sample and this one. Just go through SyncAdapter and ContactsManager once. **Maybe read the blog I mentioned**. You should probably not need a complete sample to get the idea.

Thanks & regards

**Comment by AndroidDeveloperLB** [comment] 2020-04-30 06:05
Too bad

**Closed as completed** 2020-11-11 16:10 UTC

**Comment by AndroidDeveloperLB** [comment] 2020-11-11 21:34
So it's final now... :(

**Comment by ajkh35** [comment] 2020-11-14 11:03
Yes I figured I should close the issue since it is not relevant anymore.

**Comment by AndroidDeveloperLB** [comment] 2020-11-14 11:26
@ajkh35 Do you know perhaps of a nice repository that does about the same, but in more modern way, "the way it's supposed to be done today" ?

**Comment by ajkh35** [comment] 2020-11-14 12:39
There are many repositories out there. More modern way depends upon your definition of modern. Some people would find this repository just fine, others would Find Some Other good. I do not know of any other repository though but I hope you find what you need.

Thanks & regards

**Comment by AndroidDeveloperLB** [comment] 2020-11-14 12:44
OK thank you for your time
